name: Generate 3D GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate 3D Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: atheeek
          output_dir: "profile-3d-contrib"

      - name: Commit & Push
        run: |
          git config --global user.email "atheek163@.com"
          git config --global user.name "Atheek Rahman"
          git add .
          git commit -m "🧱 Update 3D GitHub Contribution Graph" || echo "No changes to commit"
          git push
